name: LinuxDude
description: >-
  A blog dedicated to articles related to things like web development, design,
  server management...
url: 'https://linuxdude.in'
enforce_ssl: linuxdude.in
logo: /static/img/logo.png
facebook:
  app_id: 1830897697239746
defaults:
  - scope:
      path: ''
    values:
      image:
        path: /static/img/logo-card.png
        height: 800
        width: 800
markdown: kramdown
highlighter: rouge
kramdown:
  parse_block_html: true
  input: GFM
  auto_ids: true
permalink: '/p/:categories/:title.html'
related_posts_max: 4
paginate: 6
paginate_path: '/page/:num'
disqus_username: linuxdude
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - jekyll-admin
  - jekyll-toc
  - jekyll-redirect-from
commentsPath: 'https://cdn.linuxdude.in/comments/add'
